"""
full_today_summary.py - 오늘 날짜 대화 요약 모듈

파싱된 대화 중 오늘 날짜(현재까지)의 대화만 필터링하여 요약을 생성합니다.

사용법:
    python full_today_summary.py <filepath>              # 단일 파일
    python full_today_summary.py <directory>             # 디렉터리 일괄
    python full_today_summary.py --llm chatgpt <file>    # LLM 지정
    python full_today_summary.py                         # 대화형 모드
"""

import sys
from pathlib import Path

# 상위 디렉터리 모듈 import를 위한 경로 추가
sys.path.insert(0, str(Path(__file__).parent.parent))

from datetime import datetime
from typing import Optional, List

from full_config import config, LLM_PROVIDERS
from parser import KakaoLogParser
from chat_processor import ChatProcessor
from url_extractor import extract_urls_from_text, save_urls_to_file

logger = config.logger


def get_today_date() -> str:
    """오늘 날짜를 YYYY-MM-DD 형식으로 반환."""
    today = datetime.now()
    return today.strftime("%Y-%m-%d")


class TodaySummarizer:
    """오늘 날짜 대화만 요약하는 클래스."""
    
    def __init__(self, filepath: Path, provider: Optional[str] = None):
        self.filepath = filepath
        self.parser = KakaoLogParser()
        self.processor = ChatProcessor(provider)
        self.today = get_today_date()
        self.output_file = filepath.parent / f"{filepath.stem}_full_today_summary.md"

    def run(self) -> bool:
        """오늘 날짜 요약 처리를 실행."""
        if not self.filepath.exists():
            logger.error(f"File not found: {self.filepath}")
            return False

        print(f"📄 파일: {self.filepath.name}")

        logger.info(f"Parsing file: {self.filepath.name}...")
        parse_result = self.parser.parse(self.filepath)
        
        if not parse_result.messages_by_date:
            print(f"   ⚠️  파싱된 메시지가 없습니다.")
            return False

        if self.today not in parse_result.messages_by_date:
            print(f"   ℹ️  오늘({self.today}) 날짜의 대화가 없습니다.")
            return False

        messages = parse_result.messages_by_date[self.today]
        msg_count = len(messages)
        
        print(f"   ▶ {self.today} ({msg_count}개 메시지) 요약 중...")
        
        chat_content = "\n".join(messages)
        summary_result = self.processor.process_summary(chat_content)
        
        if "[ERROR]" in summary_result:
            logger.error(f"{self.today} 요약 실패: {summary_result}")
            print(f"   ❌ 요약 실패 (로그 참조)")
            return False
        
        self._save_summary(msg_count, summary_result)
        
        print(f"   ✅ 완료: {self.output_file.name}")
        return True

    def _save_summary(self, msg_count: int, summary_md: str):
        with open(self.output_file, 'w', encoding='utf-8') as f:
            f.write(f"# 📚 카카오톡 대화 요약 - {self.today}\n")
            f.write(f"- **원본 파일**: {self.filepath.name}\n")
            f.write(f"- **대상 날짜**: {self.today} (오늘)\n")
            f.write(f"- **메시지 수**: {msg_count}개\n")
            f.write(f"- **LLM**: {config.get_provider_info().name}\n")
            f.write(f"- **생성 일시**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("---\n\n")
            
            clean_summary = self._strip_headers(summary_md)
            f.write(clean_summary)
            f.write("\n\n---\n")
            f.write("_Generated by AI Assistant_\n")

    def _strip_headers(self, text: str) -> str:
        if "# 📝" not in text:
            return text
            
        lines = text.split('\n')
        start_idx = 0
        end_idx = len(lines)
        
        for i, line in enumerate(lines):
            if line.startswith("###"):
                start_idx = i
                break
        
        for i in range(len(lines)-1, -1, -1):
            if "_Generated by" in lines[i]:
                end_idx = i
                break
                
        return "\n".join(lines[start_idx:end_idx]).strip() if start_idx < end_idx else text


class TodayBatchProcessor:
    """디렉터리 내 모든 파일에서 오늘 날짜 대화를 일괄 요약."""
    
    def __init__(self, directory: Path, provider: Optional[str] = None):
        self.directory = directory
        self.provider = provider
        self.today = get_today_date()

    def get_target_files(self) -> List[Path]:
        all_txt_files = list(self.directory.glob("*.txt"))
        
        target_files = [
            f for f in all_txt_files
            if "_summary" not in f.name 
            and "_url" not in f.name
            and "_summaries" not in f.name
        ]
        
        return sorted(target_files)

    def run(self):
        if not self.directory.exists() or not self.directory.is_dir():
            print(f"❌ 유효하지 않은 디렉터리: {self.directory}")
            return

        target_files = self.get_target_files()
        
        if not target_files:
            print(f"❌ 처리할 파일이 없습니다.")
            return

        print("="*60)
        print("📅 오늘 날짜 일괄 요약")
        print("="*60)
        print(f"📂 디렉터리: {self.directory}")
        print(f"📅 대상 날짜: {self.today} (오늘)")
        print(f"🤖 LLM: {config.get_provider_info().name}")
        print(f"📄 파일 수: {len(target_files)}개")
        print("="*60 + "\n")

        results = []
        
        for filepath in target_files:
            summarizer = TodaySummarizer(filepath, self.provider)
            success = summarizer.run()
            results.append((filepath.name, success))
            print()

        self._print_results(results)

    def _print_results(self, results: List[tuple]):
        print("="*60)
        print("📋 처리 결과")
        print("="*60)
        
        success_count = sum(1 for _, success in results if success)
        skip_count = len(results) - success_count
        
        for filename, success in results:
            status = "✅ 성공" if success else "⏭️  스킵"
            print(f"  {status}: {filename}")
        
        print("-"*60)
        print(f"총 {len(results)}개 | ✅ 성공: {success_count} | ⏭️  스킵: {skip_count}")


def prompt_api_key():
    """API 키가 설정되지 않은 경우 대화형으로 입력 요청."""
    if config.get_api_key():
        return

    provider_info = config.get_provider_info()
    print("\n" + "="*50)
    print(f"🔑 API 인증 설정 ({provider_info.name})")
    print("="*50)
    print(f"환경 변수 {provider_info.env_key}가 설정되지 않았습니다.")
    
    while True:
        try:
            input_key = input(f"👉 {provider_info.name} API Key: ").strip()
            if input_key:
                config.set_api_key(input_key)
                print("✅ API Key가 설정되었습니다.\n")
                break
            else:
                print("⚠️  API Key는 비어있을 수 없습니다.")
        except KeyboardInterrupt:
            print("\n❌ 프로그램을 종료합니다.")
            sys.exit(0)


def select_llm_provider() -> str:
    """LLM 제공자 선택 프롬프트."""
    print("\n🤖 LLM 제공자 선택:")
    providers = list(LLM_PROVIDERS.keys())
    for i, key in enumerate(providers, 1):
        info = LLM_PROVIDERS[key]
        print(f"  {i}. {info.name} ({key})")
    
    while True:
        choice = input(f"\n선택 (1-{len(providers)}, 기본=1): ").strip()
        if not choice:
            return providers[0]
        if choice.isdigit() and 1 <= int(choice) <= len(providers):
            return providers[int(choice) - 1]
        print("⚠️ 올바른 번호를 선택하세요.")


def parse_args():
    """명령줄 인자 파싱."""
    args = sys.argv[1:]
    provider = None
    target = None
    
    i = 0
    while i < len(args):
        if args[i] == "--llm" and i + 1 < len(args):
            provider = args[i + 1]
            i += 2
        else:
            target = args[i]
            i += 1
    
    return target, provider


def main():
    """메인 진입점 함수."""
    today = get_today_date()
    target, provider = parse_args()
    
    # LLM 제공자 설정
    if provider:
        if provider not in LLM_PROVIDERS:
            print(f"❌ 알 수 없는 LLM: {provider}")
            print(f"   사용 가능: {', '.join(LLM_PROVIDERS.keys())}")
            sys.exit(1)
        config.set_provider(provider)
    
    print("="*50)
    print(f"📅 오늘 날짜({today}) 대화 요약기")
    print("="*50)
    
    # 명령줄 인자 없으면 대화형 모드
    if not target:
        print("Usage:")
        print("  python full_today_summary.py <file>")
        print("  python full_today_summary.py <directory>")
        print("  python full_today_summary.py --llm chatgpt <file>\n")
        
        # LLM 선택
        selected_provider = select_llm_provider()
        config.set_provider(selected_provider)
        
        # 파일/디렉터리 선택
        data_dir = config.data_dir
        if data_dir.exists():
            files = list(data_dir.glob("*.txt"))
            txt_files = [f for f in files if "_summary" not in f.name and "_url" not in f.name]
            
            if txt_files:
                print("\nAvailable files:")
                for i, f in enumerate(txt_files, 1):
                    print(f"  {i}. {f.name}")
                print(f"  A. 전체 디렉터리 처리")
                
                choice = input("\nSelect (number/A/Enter to exit): ").strip()
                
                if choice.upper() == 'A':
                    prompt_api_key()
                    processor = TodayBatchProcessor(data_dir, selected_provider)
                    processor.run()
                    sys.exit(0)
                elif choice.isdigit() and 1 <= int(choice) <= len(txt_files):
                    target_file = txt_files[int(choice)-1]
                    prompt_api_key()
                    summarizer = TodaySummarizer(target_file, selected_provider)
                    summarizer.run()
                    sys.exit(0)
        sys.exit(1)

    # 명령줄 인자로 경로가 주어진 경우
    target_path = Path(target).resolve()
    prompt_api_key()
    
    if target_path.is_dir():
        processor = TodayBatchProcessor(target_path, provider)
        processor.run()
    else:
        summarizer = TodaySummarizer(target_path, provider)
        summarizer.run()


if __name__ == "__main__":
    main()
