"""
date_summarizer.py - 날짜별 요약 메인 모듈

카카오톡 대화 파일을 날짜별로 파싱하고,
각 날짜의 대화를 요약하여 하나의 통합 리포트를 생성합니다.

사용법:
    python date_summarizer.py <filepath>              # 단일 파일 (기본 LLM)
    python date_summarizer.py <directory>             # 디렉터리 일괄 처리
    python date_summarizer.py --llm chatgpt <file>    # ChatGPT 사용
    python date_summarizer.py                         # 대화형 모드
"""

import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from config import config, LLM_PROVIDERS
from parser import KakaoLogParser
from chat_processor import ChatProcessor
from url_extractor import extract_urls_from_text, save_urls_to_file

# 전역 로거 인스턴스
logger = config.logger


class DateSummarizer:
    """
    날짜별 대화 요약 클래스.
    """
    
    def __init__(self, filepath: Path, provider: Optional[str] = None):
        """
        Args:
            filepath: 처리할 카카오톡 텍스트 파일 경로
            provider: LLM 제공자 (glm, chatgpt, minimax, perplexity)
        """
        self.filepath = filepath
        self.parser = KakaoLogParser()
        self.processor = ChatProcessor(provider)
        self.output_file = filepath.parent / f"{filepath.stem}_summaries.md"

    def run(self) -> bool:
        """날짜별 요약 처리를 실행합니다."""
        if not self.filepath.exists():
            logger.error(f"File not found: {self.filepath}")
            return False

        logger.info(f"Parsing file: {self.filepath.name}...")
        parse_result = self.parser.parse(self.filepath)
        
        if not parse_result.messages_by_date:
            logger.warning("No parsed messages found. Check file format.")
            return False

        sorted_dates = sorted(parse_result.messages_by_date.keys())
        logger.info(f"Found {parse_result.total_dates} dates.")
        
        self._initialize_output_file(len(sorted_dates))
        print(f"Processing {len(sorted_dates)} dates -> '{self.output_file.name}'")
        
        self._process_dates(sorted_dates, parse_result.messages_by_date)
        self._extract_all_urls()
        
        return True

    def _initialize_output_file(self, total_days: int):
        with open(self.output_file, 'w', encoding='utf-8') as f:
            f.write(f"# 📚 카카오톡 대화 요약 리포트\n")
            f.write(f"- **원본 파일**: {self.filepath.name}\n")
            f.write(f"- **총 대화 일수**: {total_days}일\n")
            f.write(f"- **LLM**: {config.get_provider_info().name}\n")
            f.write(f"- **생성 일시**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("---\n\n")

    def _process_dates(self, dates: List[str], messages_map: dict):
        results = []
        total = len(dates)
        
        for idx, date_key in enumerate(dates, 1):
            messages = messages_map[date_key]
            current_status = f"[{idx}/{total}] {date_key} ({len(messages)} msgs)"
            print(f"  ▶ {current_status} 요약 중...")
            
            chat_content = "\n".join(messages)
            summary_result = self.processor.process_summary(chat_content)
            
            if "[ERROR]" in summary_result:
                self._handle_error(date_key, summary_result)
                results.append(f"- {date_key}: ❌ 실패")
            else:
                self._append_summary(date_key, len(messages), summary_result)
                results.append(f"- {date_key}: ✅ 성공")

        self._print_results(results)

    def _handle_error(self, date_key: str, error_msg: str):
        # 로그 파일에 상세 에러 기록
        logger.error(f"{date_key} 요약 실패: {error_msg}")
        # 콘솔에는 간단한 메시지만
        print(f"    ❌ 실패 (로그 참조)")

    def _append_summary(self, date_key: str, msg_count: int, summary_md: str):
        clean_summary = self._strip_headers(summary_md)
        
        with open(self.output_file, 'a', encoding='utf-8') as f:
            f.write(f"\n## 📅 {date_key} ({msg_count} msg)\n\n")
            f.write(clean_summary)
            f.write("\n\n---\n")

    def _strip_headers(self, text: str) -> str:
        if "# 📝" not in text:
            return text
            
        lines = text.split('\n')
        start_idx = 0
        end_idx = len(lines)
        
        for i, line in enumerate(lines):
            if line.startswith("###"):
                start_idx = i
                break
        
        for i in range(len(lines)-1, -1, -1):
            if "_Generated by" in lines[i]:
                end_idx = i
                break
                
        return "\n".join(lines[start_idx:end_idx]).strip() if start_idx < end_idx else text

    def _extract_all_urls(self):
        print(f"  🔗 URL 추출 중...")
        try:
            full_text = self.output_file.read_text(encoding='utf-8')
            url_dict = extract_urls_from_text(full_text)
            
            if url_dict:
                url_filename = f"{self.filepath.stem}_url.txt"
                url_path = self.filepath.parent / url_filename
                save_urls_to_file(url_dict, str(url_path), self.filepath.stem)
                print(f"    ✅ {len(url_dict)}개 URL 추출 -> {url_filename}")
            else:
                print("    ℹ️  추출된 URL이 없습니다.")
        except Exception as e:
            logger.error(f"URL extraction failed: {e}")

    def _print_results(self, results: List[str]):
        print("\n  📋 날짜별 결과:")
        for res in results:
            print(f"    {res}")


class BatchProcessor:
    """디렉터리 일괄 처리 클래스."""
    
    def __init__(self, directory: Path, provider: Optional[str] = None):
        self.directory = directory
        self.provider = provider

    def get_target_files(self) -> List[Path]:
        all_txt_files = list(self.directory.glob("*.txt"))
        
        target_files = [
            f for f in all_txt_files
            if "_summary" not in f.name 
            and "_url" not in f.name
            and "_summaries" not in f.name
        ]
        
        return sorted(target_files)

    def run(self):
        if not self.directory.exists() or not self.directory.is_dir():
            print(f"❌ 유효하지 않은 디렉터리: {self.directory}")
            return

        target_files = self.get_target_files()
        
        if not target_files:
            print(f"❌ 처리할 파일이 없습니다.")
            return

        print("="*60)
        print("📁 디렉터리 일괄 처리")
        print("="*60)
        print(f"📂 디렉터리: {self.directory}")
        print(f"🤖 LLM: {config.get_provider_info().name}")
        print(f"📄 파일 수: {len(target_files)}개")
        print("="*60 + "\n")

        for i, f in enumerate(target_files, 1):
            print(f"   {i}. {f.name}")
        print()

        confirm = input("계속 진행하시겠습니까? (Y/n): ").strip().lower()
        if confirm == 'n':
            print("❌ 취소되었습니다.")
            return

        print("\n" + "-"*60)

        results = []
        total = len(target_files)
        
        for idx, filepath in enumerate(target_files, 1):
            print(f"\n[{idx}/{total}] 📄 {filepath.name}")
            
            try:
                summarizer = DateSummarizer(filepath, self.provider)
                success = summarizer.run()
                results.append((filepath.name, "✅ 성공" if success else "⚠️ 스킵"))
            except Exception as e:
                logger.exception(f"Failed to process {filepath.name}")
                results.append((filepath.name, f"❌ 실패"))

        self._print_final_results(results)

    def _print_final_results(self, results: List[tuple]):
        print("\n" + "="*60)
        print("📋 최종 결과")
        print("="*60)
        
        success_count = sum(1 for _, status in results if "성공" in status)
        
        for filename, status in results:
            print(f"  {status} {filename}")
        
        print("-"*60)
        print(f"총 {len(results)}개 | ✅ 성공: {success_count} | 기타: {len(results) - success_count}")


def prompt_api_key():
    """API 키가 설정되지 않은 경우 대화형으로 입력 요청."""
    if config.get_api_key():
        return

    provider_info = config.get_provider_info()
    print("\n" + "="*50)
    print(f"🔑 API 인증 설정 ({provider_info.name})")
    print("="*50)
    print(f"환경 변수 {provider_info.env_key}가 설정되지 않았습니다.")
    
    while True:
        try:
            input_key = input(f"👉 {provider_info.name} API Key: ").strip()
            if input_key:
                config.set_api_key(input_key)
                print("✅ API Key가 설정되었습니다.\n")
                break
            else:
                print("⚠️  API Key는 비어있을 수 없습니다.")
        except KeyboardInterrupt:
            print("\n❌ 프로그램을 종료합니다.")
            sys.exit(0)


def select_llm_provider() -> str:
    """LLM 제공자 선택 프롬프트."""
    print("\n🤖 LLM 제공자 선택:")
    providers = list(LLM_PROVIDERS.keys())
    for i, key in enumerate(providers, 1):
        info = LLM_PROVIDERS[key]
        print(f"  {i}. {info.name} ({key})")
    
    while True:
        choice = input(f"\n선택 (1-{len(providers)}, 기본=1): ").strip()
        if not choice:
            return providers[0]
        if choice.isdigit() and 1 <= int(choice) <= len(providers):
            return providers[int(choice) - 1]
        print("⚠️ 올바른 번호를 선택하세요.")


def parse_args():
    """명령줄 인자 파싱."""
    args = sys.argv[1:]
    provider = None
    target = None
    
    i = 0
    while i < len(args):
        if args[i] == "--llm" and i + 1 < len(args):
            provider = args[i + 1]
            i += 2
        else:
            target = args[i]
            i += 1
    
    return target, provider


def main():
    """메인 진입점 함수."""
    target, provider = parse_args()
    
    # LLM 제공자 설정
    if provider:
        if provider not in LLM_PROVIDERS:
            print(f"❌ 알 수 없는 LLM: {provider}")
            print(f"   사용 가능: {', '.join(LLM_PROVIDERS.keys())}")
            sys.exit(1)
        config.set_provider(provider)
    
    # 명령줄 인자 없으면 대화형 모드
    if not target:
        print("Usage:")
        print("  python date_summarizer.py <file>               # 단일 파일")
        print("  python date_summarizer.py <directory>          # 디렉터리")
        print("  python date_summarizer.py --llm chatgpt <file> # LLM 지정\n")
        
        # LLM 선택
        selected_provider = select_llm_provider()
        config.set_provider(selected_provider)
        
        # 파일/디렉터리 선택
        data_dir = config.data_dir
        if data_dir.exists():
            files = list(data_dir.glob("*.txt"))
            txt_files = [f for f in files if "_summary" not in f.name and "_url" not in f.name]
            
            if txt_files:
                print("\nAvailable files:")
                for i, f in enumerate(txt_files, 1):
                    print(f"  {i}. {f.name}")
                print(f"  A. 전체 디렉터리 처리")
                
                choice = input("\nSelect (number/A/Enter to exit): ").strip()
                
                if choice.upper() == 'A':
                    prompt_api_key()
                    processor = BatchProcessor(data_dir, selected_provider)
                    processor.run()
                    sys.exit(0)
                elif choice.isdigit() and 1 <= int(choice) <= len(txt_files):
                    target_file = txt_files[int(choice)-1]
                    prompt_api_key()
                    summarizer = DateSummarizer(target_file, selected_provider)
                    summarizer.run()
                    sys.exit(0)
        sys.exit(1)

    # 명령줄 인자로 경로가 주어진 경우
    target_path = Path(target).resolve()
    prompt_api_key()
    
    if target_path.is_dir():
        processor = BatchProcessor(target_path, provider)
        processor.run()
    else:
        summarizer = DateSummarizer(target_path, provider)
        summarizer.run()


if __name__ == "__main__":
    main()
